spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/springShop1.1
    username: root
    password: 123
  flyway:
    baseline-on-migrate: true
server:
  port: 5050
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG


logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


logging.file: logs/application.log
